global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring'
    static_configs:
      - targets: ['spring:8080', 'spring2:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']