services:

  # 현재 api.2025skufestival.site:3306 masterpiece 사용중
  spring1: # 서비스 이름
    container_name: spring-skufestival-1
    ports: # 포트 지정
      - "8080:8080"
    image: jd1019/back-skufestival:v2 # 사용하고자 하는 이미지
    environment:
      - SPRING_PROFILE=prod
    restart: always
    networks:
      - festival # 네트워크

  spring2: # 서비스 이름
    container_name: spring-skufestival-2
    ports: # 포트 지정
      - "8081:8080"
    image: jd1019/back-skufestival:v2 # 사용하고자 하는 이미지
    environment:
      - SPRING_PROFILE=prod
    restart: always
    networks:
      - festival # 네트워크

  spring3: # 서비스 이름
    container_name: spring-skufestival-3
    ports: # 포트 지정
      - "8082:8080"
    image: jd1019/back-skufestival:v2 # 사용하고자 하는 이미지
    environment:
      - SPRING_PROFILE=prod
    restart: always
    networks:
      - festival # 네트워크

  nginx:
    container_name: nginx-skufestival
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - festival

  react:
    container_name: react-skufestival
    ports:
      - "3000:3000"
      - "5173:5173"
    image: jd1019/front-skufestival:v3
    restart: always
    networks:
      - festival

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - festival
    restart: always

networks:
  festival:
    external: true  # 외부 네트워크 사용